### ISSUE TITLE
Bump WordPress version in the readme.txt

### ISSUE THREAD

**Issue by lukecav** [redirectionio/proxy-wordpress#2]
https://plugins.svn.wordpress.org/redirection-io/trunk/readme.txt
Tested up to: 4.8

Should be 
**Tested up to: 5.1**

This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

**Comment by lyrixx** [comment]
Hello. Thanks for you issue but we stopped the support for this projet.
You can find more information in this [commit](https://github.com/redirectionio/proxy-wordpress/commit/3d7ab784158d8faa7ab863891ed3c113f2a99d04)
